// <auto-generated />
namespace DoctorAppointmentSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class createSlotModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createSlotModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202012081041107_createSlotModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
